CREATE TABLE IF NOT EXISTS `invoices` (
  `id` char(36) NOT NULL DEFAULT uuid(),
  `number` varchar(100) NOT NULL UNIQUE COMMENT 'Consecutivo DIAN ej: FAC-1002',
  `dian_resolution` varchar(255) DEFAULT NULL,
  `sale_id` varchar(100) NOT NULL COMMENT 'ID de admin_sales o orders',
  `sale_type` enum('admin', 'client') NOT NULL DEFAULT 'admin',
  `customer_name` varchar(255) NOT NULL,
  `customer_email` varchar(255) DEFAULT NULL,
  `customer_document` varchar(50) DEFAULT NULL,
  `subtotal` decimal(12,2) NOT NULL,
  `tax` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total` decimal(12,2) NOT NULL,
  `payment_method` varchar(50) NOT NULL,
  `status` enum('draft', 'issued', 'paid', 'cancelled') DEFAULT 'issued',
  `issued_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `due_date` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_invoices_number` (`number`),
  KEY `idx_invoices_sale_id` (`sale_id`),
  KEY `idx_invoices_status` (`status`),
  KEY `idx_invoices_issued_date` (`issued_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
